FROM node:20 as BUILDER

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY  . .

RUN npm run build

# gunakan web server Nginx untuk menyajikan build React
FROM nginx:stable-alpine

# hapus default file nginx
RUN rm -rf /usr/share/nginx/html/*

# copy file build react ke direktory hosting nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# menyalin configurasi nginx custom
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]