version: "3.9"

services:
  backend:
    image: ghcr.io/ariyalex/ai-learning-insight-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: ["/bin/sh", "/src/entrypoint.sh"]

  # ml:
  #   image: ghcr.io/ariyalex/postgres:15
  #   env_file:
  #     - ./ml/.env
  #   ports:
  #     - "8000:8000"
  #   command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]