services:
  backend:
    image: ghcr.io/ariyalex/ai-learning-insight-backend:latest
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - ml
    entrypoint: ["/bin/sh", "/src/entrypoint.sh"]
    ports:
      - "3000:3000"
    networks:
      - internal
      - public

  ml:
    image: ghcr.io/ariyalex/ai-learning-insight-ml:latest
    env_file:
      - ./ml/.env
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    expose:
      - "8000"
    networks:
      - internal
      - public

  frontend:
    image: ghcr.io/ariyalex/ai-learning-insight-frontend:latest
    container_name: frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    networks:
      - internal
      - public
