version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: capstone
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ai_learning_insight
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/src
      # - backend-data:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - ml
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - internal
      - public

  ml:
    build:
      context: ./ml
      dockerfile: dockerfile
    env_file:
      - ./ml/.env
    volumes:
      - ./ml:/app
      # - ml-data:/app
      - /app/__pycache__
    networks:
      - internal
      - public
    command:
      ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  db-data:
  backend-data:
  ml-data:

networks:
  internal:
    internal: true
  public:
    driver: bridge
